version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
